import {
  Conversation,
  Message,
  Customer,
  Lead,
  FAQ,
  ProductItem,
  ServiceItem,
  PriceItem,
  AutomationRule,
  ConsentRecord,
  DataRequest,
  GrievanceTicket,
  AuditLog,
  ErrorLog,
  SystemHealthItem,
  NotificationItem,
  Vendor,
  RetentionPolicy,
} from './types';

export const initialCustomers: Customer[] = [
  {
    id: 'c1111111-1111-1111-1111-111111111111',
    name: 'Amit Verma',
    phone: '+919876543210',
    location: 'Mumbai, MH',
    tags: ['VIP', 'Commercial'],
    is_anonymized: false,
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'c2222222-2222-2222-2222-222222222222',
    name: 'Sunita Rao',
    phone: '+919812345678',
    location: 'Bengaluru, KA',
    tags: ['Residential', 'Urgent'],
    is_anonymized: false,
    created_at: '2026-08-15T14:30:00Z',
  },
  {
    id: 'c3333333-3333-3333-3333-333333333333',
    name: 'Rajesh Gupta',
    phone: '+919711223344',
    location: 'Delhi NCR',
    tags: ['Industrial'],
    is_anonymized: false,
    created_at: '2026-08-01T09:15:00Z',
  },
  {
    id: 'c4444444-4444-4444-4444-444444444444',
    name: 'Ananya Deshmukh',
    phone: '+919655443322',
    location: 'Pune, MH',
    tags: ['General Enquiry'],
    is_anonymized: false,
    created_at: '2026-08-18T16:00:00Z',
  },
  {
    id: 'c5555555-5555-5555-5555-555555555555',
    name: 'Anonymized User',
    phone: '+91-XXXX-XXXX-c555',
    location: 'Redacted',
    tags: ['ANONYMIZED'],
    is_anonymized: true,
    anonymized_at: '2026-08-17T11:00:00Z',
    created_at: '2026-07-20T12:00:00Z',
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 'b1111111-1111-1111-1111-111111111111',
    customer_id: 'c1111111-1111-1111-1111-111111111111',
    customer_name: 'Amit Verma',
    customer_phone: '+919876543210',
    customer_location: 'Mumbai, MH',
    tags: ['VIP', 'Commercial'],
    status: 'OPEN',
    mode: 'HUMAN',
    assigned_to: 'a2222222-2222-2222-2222-222222222222',
    assigned_name: 'Rahul Sharma',
    unread_count: 2,
    last_message: 'Hi Amit! I am Rahul Sharma from Kedar Enterprises. I have taken over this chat.',
    last_message_at: '5 mins ago',
    intent: 'Commercial Quotation Request',
    confidence: 0.96,
    urgency: 'HIGH',
  },
  {
    id: 'b2222222-2222-2222-2222-222222222222',
    customer_id: 'c2222222-2222-2222-2222-222222222222',
    customer_name: 'Sunita Rao',
    customer_phone: '+919812345678',
    customer_location: 'Bengaluru, KA',
    tags: ['Residential', 'Urgent'],
    status: 'OPEN',
    mode: 'BOT',
    unread_count: 0,
    last_message: '🏢 Kedar Enterprises Working Hours: Mon-Sat 9 AM - 6 PM IST.',
    last_message_at: '30 mins ago',
    intent: 'Business Hours & Location FAQ',
    confidence: 0.99,
    urgency: 'LOW',
  },
  {
    id: 'b3333333-3333-3333-3333-333333333333',
    customer_id: 'c3333333-3333-3333-3333-333333333333',
    customer_name: 'Rajesh Gupta',
    customer_phone: '+919711223344',
    customer_location: 'Delhi NCR',
    tags: ['Industrial'],
    status: 'RESOLVED',
    mode: 'BOT',
    unread_count: 0,
    last_message: 'Thank you for choosing Kedar Enterprises! Your annual contract is active.',
    last_message_at: '2 days ago',
    intent: 'Service Contract Confirmation',
    confidence: 0.98,
    urgency: 'LOW',
  },
  {
    id: 'b4444444-4444-4444-4444-444444444444',
    customer_id: 'c4444444-4444-4444-4444-444444444444',
    customer_name: 'Ananya Deshmukh',
    customer_phone: '+919655443322',
    customer_location: 'Pune, MH',
    tags: ['General Enquiry'],
    status: 'OPEN',
    mode: 'BOT',
    unread_count: 1,
    last_message: 'How can I get product brochures for solar inverters?',
    last_message_at: '10 mins ago',
    intent: 'Product Brochure Request',
    confidence: 0.91,
    urgency: 'MEDIUM',
  },
];

export const initialMessagesMap: Record<string, Message[]> = {
  'b1111111-1111-1111-1111-111111111111': [
    {
      id: 'm101',
      conversation_id: 'b1111111-1111-1111-1111-111111111111',
      direction: 'INBOUND',
      message_type: 'text',
      content: 'Hello, I need pricing details for commercial HVAC installations for our 5-floor building in Mumbai.',
      sender_type: 'CUSTOMER',
      status: 'READ',
      created_at: '11:25 AM',
    },
    {
      id: 'm102',
      conversation_id: 'b1111111-1111-1111-1111-111111111111',
      direction: 'OUTBOUND',
      message_type: 'text',
      content: '👋 Welcome to Kedar Enterprises!\n\n1️⃣ Products / Services\n2️⃣ Price Enquiry\n3️⃣ Make an Enquiry\n4️⃣ Business Info\n5️⃣ Talk to Team',
      sender_type: 'BOT',
      status: 'DELIVERED',
      created_at: '11:25 AM',
      confidence: 1.0,
      sources: ['KE-WA-Main-Inbound', 'Deterministic Menu'],
    },
    {
      id: 'm103',
      conversation_id: 'b1111111-1111-1111-1111-111111111111',
      direction: 'INBOUND',
      message_type: 'text',
      content: 'Can I talk to a human expert right now? Option 5 please.',
      sender_type: 'CUSTOMER',
      status: 'READ',
      created_at: '11:35 AM',
    },
    {
      id: 'm104',
      conversation_id: 'b1111111-1111-1111-1111-111111111111',
      direction: 'OUTBOUND',
      message_type: 'text',
      content: 'Hi Amit! I am Rahul Sharma from Kedar Enterprises. I have taken over this chat. Let me share our commercial product catalog with you.',
      sender_type: 'STAFF',
      status: 'DELIVERED',
      created_at: '11:40 AM',
    },
  ],
  'b2222222-2222-2222-2222-222222222222': [
    {
      id: 'm201',
      conversation_id: 'b2222222-2222-2222-2222-222222222222',
      direction: 'INBOUND',
      message_type: 'text',
      content: 'What are your working hours and office location in Bengaluru?',
      sender_type: 'CUSTOMER',
      status: 'READ',
      created_at: '11:15 AM',
    },
    {
      id: 'm202',
      conversation_id: 'b2222222-2222-2222-2222-222222222222',
      direction: 'OUTBOUND',
      message_type: 'text',
      content: '🏢 Kedar Enterprises Working Hours:\nMonday–Saturday: 09:00 AM – 06:00 PM IST.\n\n📍 Office Location: MG Road, Bengaluru, Karnataka.',
      sender_type: 'BOT',
      status: 'DELIVERED',
      created_at: '11:15 AM',
      confidence: 0.99,
      sources: ['Supabase Verified Knowledge', 'FAQ: Hours & Office'],
    },
  ],
  'b3333333-3333-3333-3333-333333333333': [
    {
      id: 'm301',
      conversation_id: 'b3333333-3333-3333-3333-333333333333',
      direction: 'INBOUND',
      message_type: 'text',
      content: 'Confirming industrial generator annual contract renewal for Delhi unit.',
      sender_type: 'CUSTOMER',
      status: 'READ',
      created_at: '2 days ago',
    },
    {
      id: 'm302',
      conversation_id: 'b3333333-3333-3333-3333-333333333333',
      direction: 'OUTBOUND',
      message_type: 'text',
      content: 'Thank you for choosing Kedar Enterprises! Your annual contract is active.',
      sender_type: 'BOT',
      status: 'DELIVERED',
      created_at: '2 days ago',
      confidence: 0.98,
      sources: ['n8n Contract Flow'],
    },
  ],
  'b4444444-4444-4444-4444-444444444444': [
    {
      id: 'm401',
      conversation_id: 'b4444444-4444-4444-4444-444444444444',
      direction: 'INBOUND',
      message_type: 'text',
      content: 'How can I get product brochures for solar inverters?',
      sender_type: 'CUSTOMER',
      status: 'READ',
      created_at: '11:35 AM',
    },
  ],
};

export const initialLeads: Lead[] = [
  {
    id: 'l1111111-1111-1111-1111-111111111111',
    customer_id: 'c1111111-1111-1111-1111-111111111111',
    customer_name: 'Amit Verma',
    customer_phone: '+919876543210',
    requirement: '5-floor commercial HVAC installation & maintenance setup',
    product: 'Commercial HVAC Solutions',
    status: 'QUALIFIED',
    assigned_to: 'a2222222-2222-2222-2222-222222222222',
    assigned_name: 'Rahul Sharma',
    score: 92,
    follow_up_date: '2026-08-22',
    notes: 'Requested custom quotation for Mumbai site inspection.',
    created_at: '2026-08-19T10:00:00Z',
  },
  {
    id: 'l2222222-2222-2222-2222-222222222222',
    customer_id: 'c2222222-2222-2222-2222-222222222222',
    customer_name: 'Sunita Rao',
    customer_phone: '+919812345678',
    requirement: 'Residential solar inverter unit installation',
    product: 'Solar Power Units',
    status: 'NEW',
    score: 75,
    follow_up_date: '2026-08-21',
    notes: 'Inquired via WhatsApp automation keyword menu.',
    created_at: '2026-08-20T08:30:00Z',
  },
  {
    id: 'l3333333-3333-3333-3333-333333333333',
    customer_id: 'c3333333-3333-3333-3333-333333333333',
    customer_name: 'Rajesh Gupta',
    customer_phone: '+919711223344',
    requirement: 'Industrial generator annual service contract',
    product: 'Industrial Generators',
    status: 'CONVERTED',
    assigned_to: 'a3333333-3333-3333-3333-333333333333',
    assigned_name: 'Priya Patel',
    score: 98,
    follow_up_date: '2026-09-15',
    notes: 'Contract signed & payment confirmed.',
    created_at: '2026-08-15T12:00:00Z',
  },
];

export const initialFaqs: FAQ[] = [
  {
    id: 'f1111111-1111-1111-1111-111111111111',
    question: 'What are your working hours?',
    answer: 'Our business hours are Monday through Saturday, 9:00 AM to 6:00 PM IST. We remain closed on Sundays and National Holidays.',
    keywords: ['hours', 'timing', 'open', 'working hours', 'time'],
    category: 'General Info',
    enabled: true,
    match_count: 48,
    status: 'APPROVED',
  },
  {
    id: 'f2222222-2222-2222-2222-222222222222',
    question: 'Where is your main office located?',
    answer: 'Kedar Enterprises head office is located at Plot 45, Industrial Suburb Stage II, Bengaluru, Karnataka - 560022.',
    keywords: ['address', 'location', 'office', 'where', 'map'],
    category: 'General Info',
    enabled: true,
    match_count: 32,
    status: 'APPROVED',
  },
  {
    id: 'f3333333-3333-3333-3333-333333333333',
    question: 'How can I request a price quotation?',
    answer: 'You can type "Enquiry" or select option 3 in our WhatsApp main menu. A sales consultant will contact you within 2 business hours.',
    keywords: ['price', 'quote', 'cost', 'rates', 'catalog', 'enquiry'],
    category: 'Sales',
    enabled: true,
    match_count: 76,
    status: 'APPROVED',
  },
];

export const initialProducts: ProductItem[] = [
  {
    id: 'p1',
    sku: 'KE-HVAC-VRF-500',
    name: 'Commercial VRF Multi-Split HVAC System',
    category: 'HVAC Systems',
    description: 'High efficiency variable refrigerant flow system suitable for multi-floor commercial complexes.',
    unit: 'system',
    price: 450000,
    status: 'APPROVED',
    updated_at: '2026-08-15',
  },
  {
    id: 'p2',
    sku: 'KE-SOLAR-INV-10K',
    name: '10kVA Industrial Solar Hybrid Inverter',
    category: 'Renewable Power',
    description: 'Heavy duty pure sine wave hybrid solar inverter with MPPT charge controller.',
    unit: 'unit',
    price: 185000,
    status: 'APPROVED',
    updated_at: '2026-08-18',
  },
  {
    id: 'p3',
    sku: 'KE-GEN-IND-75',
    name: '75kVA Silent Diesel Industrial Generator',
    category: 'Power Equipment',
    description: 'Acoustic canopy silent generator with CPCB IV+ compliance for industrial facilities.',
    unit: 'unit',
    price: 620000,
    status: 'APPROVED',
    updated_at: '2026-08-10',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 's1',
    name: 'Comprehensive Annual Maintenance Contract (AMC)',
    category: 'HVAC Servicing',
    description: 'Full-scope quarterly preventive maintenance, emergency breakdown repairs, and parts replacement.',
    scope: '4 scheduled visits/year + unlimited breakdown calls',
    sla: '4-hour emergency response guarantee in metro zones',
    status: 'APPROVED',
    updated_at: '2026-08-12',
  },
  {
    id: 's2',
    name: 'Commercial Energy & HVAC Site Audit',
    category: 'Consulting',
    description: 'Comprehensive thermographic building scan and HVAC energy consumption optimization analysis.',
    scope: 'On-site technical evaluation + official certified audit report',
    sla: 'Report delivered within 5 business days',
    status: 'APPROVED',
    updated_at: '2026-08-16',
  },
];

export const initialPrices: PriceItem[] = [
  {
    id: 'pr1',
    item_name: 'Commercial VRF Maintenance Package',
    price: 25000,
    currency: 'INR',
    unit: 'year / unit',
    pricing_type: 'SUBSCRIPTION',
    status: 'AUTHORITATIVE',
    updated_at: '2026-08-15',
  },
  {
    id: 'pr2',
    item_name: 'Site Inspection & Engineering Evaluation',
    price: 3500,
    currency: 'INR',
    unit: 'visit',
    pricing_type: 'STANDARD',
    status: 'AUTHORITATIVE',
    updated_at: '2026-08-16',
  },
  {
    id: 'pr3',
    item_name: 'Industrial Generator Routine AMC',
    price: 48000,
    currency: 'INR',
    unit: 'annual',
    pricing_type: 'SUBSCRIPTION',
    status: 'AUTHORITATIVE',
    updated_at: '2026-08-10',
  },
];

export const initialAutomationRules: AutomationRule[] = [
  {
    id: 'r1',
    name: 'Welcome Menu Greeting',
    description: 'Sends standard welcoming message with 5 options on initial customer contact',
    trigger_event: 'FIRST_MESSAGE',
    enabled: true,
    success_count: 342,
    failure_count: 0,
    latency_ms: 120,
  },
  {
    id: 'r2',
    name: 'Deterministic FAQ Matcher',
    description: 'Retrieves relevant FAQ answer based on exact keyword search in Supabase DB',
    trigger_event: 'KEYWORD_MATCH',
    enabled: true,
    success_count: 512,
    failure_count: 2,
    latency_ms: 85,
  },
  {
    id: 'r3',
    name: 'Lead Qualification Capture',
    description: 'Captures name, requirement, and location through conversational state flow',
    trigger_event: 'MENU_OPTION_3',
    enabled: true,
    success_count: 128,
    failure_count: 1,
    latency_ms: 140,
  },
  {
    id: 'r4',
    name: 'Human Takeover Router',
    description: 'Changes mode to HUMAN and alerts available staff dashboard upon human request',
    trigger_event: 'HUMAN_REQUEST',
    enabled: true,
    success_count: 44,
    failure_count: 0,
    latency_ms: 60,
  },
  {
    id: 'r5',
    name: '24-Hour Follow-Up Cron',
    description: 'Sends approved Meta WhatsApp template to pending leads after 24 hours',
    trigger_event: 'SCHEDULED_CRON',
    enabled: true,
    success_count: 89,
    failure_count: 0,
    latency_ms: 310,
  },
];

export const initialSystemHealth: SystemHealthItem[] = [
  {
    name: 'WhatsApp Cloud API',
    service: 'Meta Graph API v20.0',
    status: 'OPERATIONAL',
    latency_ms: 180,
    last_check: 'Just now',
    uptime: '99.98%',
    description: 'Inbound & outbound message transport active',
  },
  {
    name: 'Supabase PostgreSQL',
    service: 'Database & Auth (AWS Mumbai)',
    status: 'OPERATIONAL',
    latency_ms: 42,
    last_check: 'Just now',
    uptime: '99.99%',
    description: 'Consent ledger, chats, knowledge tables synced',
  },
  {
    name: 'n8n Workflow Engine',
    service: 'KE-WA Automation Cluster',
    status: 'OPERATIONAL',
    latency_ms: 110,
    last_check: 'Just now',
    uptime: '99.95%',
    description: 'All 6 webhook pipelines executing cleanly',
  },
  {
    name: 'AI Router Engine',
    service: 'Next.js Edge API (/api/ai/router)',
    status: 'OPERATIONAL',
    latency_ms: 95,
    last_check: 'Just now',
    uptime: '100.0%',
    description: 'Deterministic intent + Guardrail active',
  },
  {
    name: 'Groq (Primary LLM)',
    service: 'llama-3.3-70b-versatile',
    status: 'OPERATIONAL',
    latency_ms: 290,
    last_check: '1 min ago',
    uptime: '99.91%',
    description: 'Primary generation provider',
  },
  {
    name: 'Gemini (Secondary LLM)',
    service: 'gemini-1.5-pro / flash',
    status: 'OPERATIONAL',
    latency_ms: 410,
    last_check: '1 min ago',
    uptime: '99.96%',
    description: 'Secondary fallback & intent validation',
  },
  {
    name: 'OpenRouter (Fallback)',
    service: 'Multi-model aggregator',
    status: 'OPERATIONAL',
    latency_ms: 480,
    last_check: '2 mins ago',
    uptime: '99.85%',
    description: 'Emergency tertiary routing layer',
  },
  {
    name: 'Knowledge Retrieval',
    service: 'pgvector & keyword index',
    status: 'OPERATIONAL',
    latency_ms: 28,
    last_check: 'Just now',
    uptime: '100.0%',
    description: '100% verified knowledge grounding active',
  },
  {
    name: 'Follow-up Engine',
    service: 'Meta Template Cron Daemon',
    status: 'OPERATIONAL',
    latency_ms: 70,
    last_check: '5 mins ago',
    uptime: '99.94%',
    description: 'Automated 24-hour lead reminders scheduled',
  },
  {
    name: 'DPDP Automation',
    service: 'Compliance & Erasure Cron',
    status: 'OPERATIONAL',
    latency_ms: 35,
    last_check: 'Just now',
    uptime: '100.0%',
    description: 'Consent validation & audit trails immutable',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Urgent Staff Handoff Requested',
    message: 'Amit Verma requested live human assistance for Commercial HVAC Quotation.',
    category: 'HANDOFF',
    priority: 'HIGH',
    read: false,
    created_at: '5 mins ago',
    target_url: '/inbox',
  },
  {
    id: 'notif-2',
    title: 'New Commercial Lead Captured',
    message: 'Sunita Rao captured via WhatsApp menu for Residential Solar Inverter.',
    category: 'LEAD',
    priority: 'MEDIUM',
    read: false,
    created_at: '30 mins ago',
    target_url: '/leads',
  },
  {
    id: 'notif-3',
    title: 'DPDP Right-to-Erasure Completed',
    message: 'Customer record c5555555 successfully anonymized and scrubbed from live records.',
    category: 'DPDP',
    priority: 'MEDIUM',
    read: true,
    created_at: 'Yesterday',
    target_url: '/privacy',
  },
  {
    id: 'notif-4',
    title: 'Meta API Webhook Heartbeat 200 OK',
    message: 'Cloud API Webhook verified and responding with 42ms response latency.',
    category: 'SYSTEM',
    priority: 'LOW',
    read: true,
    created_at: 'Today, 08:00 AM',
    target_url: '/settings',
  },
];

export const initialErrorLogs: ErrorLog[] = [
  {
    id: 'err-101',
    severity: 'LOW',
    service: 'AI Router',
    message: 'Unknown keyword query routed to deterministic fallback',
    timestamp: 'Today, 10:14 AM',
    sanitized_trace: 'IntentAnalyzer.evaluate(query="XYZ unknown") -> FALLBACK_GUARD',
    resolved: true,
  },
  {
    id: 'err-102',
    severity: 'MEDIUM',
    service: 'n8n Webhook',
    message: 'Transient WhatsApp Graph API rate limit warning (recovered in 200ms)',
    timestamp: 'Yesterday, 04:30 PM',
    sanitized_trace: 'GraphAPI.postMessage() -> HTTP 429 [Recovered via Exponential Backoff]',
    resolved: true,
  },
];

export const initialConsentRecords: ConsentRecord[] = [
  {
    id: 'cs1',
    customer_id: 'c1111111-1111-1111-1111-111111111111',
    customer_name: 'Amit Verma',
    customer_phone: '+919876543210',
    purpose: 'WhatsApp Business Service Communication & Lead Qualification',
    status: 'GRANTED',
    notice_version: 'v1.0-2024',
    source: 'WHATSAPP_OPTIN',
    granted_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'cs2',
    customer_id: 'c2222222-2222-2222-2222-222222222222',
    customer_name: 'Sunita Rao',
    customer_phone: '+919812345678',
    purpose: 'WhatsApp Business Service Communication',
    status: 'GRANTED',
    notice_version: 'v1.0-2024',
    source: 'WHATSAPP_OPTIN',
    granted_at: '2026-08-15T14:30:00Z',
  },
  {
    id: 'cs3',
    customer_id: 'c5555555-5555-5555-5555-555555555555',
    customer_name: 'Anonymized User',
    customer_phone: '+91-XXXX-XXXX-c555',
    purpose: 'WhatsApp Communication',
    status: 'WITHDRAWN',
    notice_version: 'v1.0-2024',
    source: 'ERASURE_REQUEST',
    granted_at: '2026-07-20T12:00:00Z',
  },
];

export const initialDataRequests: DataRequest[] = [
  {
    id: 'dr1',
    customer_id: 'c5555555-5555-5555-5555-555555555555',
    customer_name: 'Anonymized User',
    customer_phone: '+91-XXXX-XXXX-c555',
    request_type: 'ERASURE',
    status: 'COMPLETED',
    details: 'Customer requested full deletion of personal phone and chat history under DPDP Act 2023 Sec 12.',
    resolution_notes: 'Executed anonymize_customer_data SQL procedure. Personal phone redacted.',
    requested_at: '2026-08-17T09:00:00Z',
  },
  {
    id: 'dr2',
    customer_id: 'c2222222-2222-2222-2222-222222222222',
    customer_name: 'Sunita Rao',
    customer_phone: '+919812345678',
    request_type: 'ACCESS',
    status: 'IN_PROGRESS',
    details: 'Requested export summary of stored personal data & lead details.',
    requested_at: '2026-08-19T14:00:00Z',
  },
];

export const initialGrievanceTickets: GrievanceTicket[] = [
  {
    id: 'gt1',
    ticket_number: 'KE-DPDP-2026-001',
    customer_name: 'Ananya Deshmukh',
    issue: 'Inquired how customer WhatsApp phone number was sourced for business message.',
    category: 'Privacy/Consent',
    status: 'OPEN',
    created_at: '2026-08-18T16:00:00Z',
  },
  {
    id: 'gt2',
    ticket_number: 'KE-DPDP-2026-002',
    customer_name: 'Anonymized User',
    issue: 'Requested written confirmation of data anonymization.',
    category: 'Data Erasure',
    status: 'RESOLVED',
    created_at: '2026-08-17T11:00:00Z',
    resolution: 'Confirmation letter issued; database record anonymized.',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'al1',
    user_name: 'Kedar Administrator',
    action: 'ADMIN_LOGIN',
    resource_type: 'users',
    metadata: '{"method": "password_auth", "status": "SUCCESS"}',
    ip_address: '103.21.124.5',
    created_at: 'Today, 09:00 AM',
  },
  {
    id: 'al2',
    user_name: 'Rahul Sharma',
    action: 'HUMAN_TAKEOVER_INITIATED',
    resource_type: 'conversations',
    metadata: '{"conversation_id": "b1111111-1111-1111-1111-111111111111", "mode": "HUMAN"}',
    ip_address: '103.21.124.88',
    created_at: 'Today, 11:40 AM',
  },
  {
    id: 'al3',
    user_name: 'Kedar Administrator',
    action: 'DPDP_DATA_ERASURE_EXECUTED',
    resource_type: 'customers',
    metadata: '{"customer_id": "c5555555-5555-5555-5555-555555555555", "statute": "DPDP_2023"}',
    ip_address: '103.21.124.5',
    created_at: 'Yesterday, 04:15 PM',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'v1',
    vendor_name: 'Meta Platforms Ireland / India',
    service_provided: 'WhatsApp Cloud API Transport',
    data_shared: 'WhatsApp Phone Number, Encrypted Payload',
    data_location: 'Meta Cloud (EU / Global Nodes)',
    contract_status: 'ACTIVE',
    last_security_audit: '2026-01-15',
  },
  {
    id: 'v2',
    vendor_name: 'Supabase Inc.',
    service_provided: 'PostgreSQL Managed Database & Auth',
    data_shared: 'Customer Data, Messages, Logs',
    data_location: 'AWS Mumbai (ap-south-1)',
    contract_status: 'ACTIVE',
    last_security_audit: '2026-02-10',
  },
  {
    id: 'v3',
    vendor_name: 'n8n Cloud / VPS',
    service_provided: 'Workflow Automation Engine',
    data_shared: 'Event Webhook Payloads (Ephemeral)',
    data_location: 'Secured Cloud VPS',
    contract_status: 'ACTIVE',
    last_security_audit: '2026-03-01',
  },
  {
    id: 'v4',
    vendor_name: 'Vercel Inc.',
    service_provided: 'Dashboard Web Application Hosting',
    data_shared: 'No Direct DB Data (Client Side Only)',
    data_location: 'Vercel Global Edge Network',
    contract_status: 'ACTIVE',
    last_security_audit: '2026-01-20',
  },
];

export const initialRetentionPolicies: RetentionPolicy[] = [
  {
    id: 'rp1',
    data_category: 'Customer Messages & Chat Logs',
    retention_period_days: 180,
    auto_purge: true,
    legal_basis: 'DPDP Act 2023 Sec 8(7) Purpose Limitation',
  },
  {
    id: 'rp2',
    data_category: 'Qualified Lead Records',
    retention_period_days: 365,
    auto_purge: false,
    legal_basis: 'Commercial Contractual Necessity',
  },
  {
    id: 'rp3',
    data_category: 'Consent Ledger Records',
    retention_period_days: 1095,
    auto_purge: false,
    legal_basis: 'Statutory Compliance Record Keeping',
  },
  {
    id: 'rp4',
    data_category: 'System Security Audit Logs',
    retention_period_days: 730,
    auto_purge: true,
    legal_basis: 'Information Technology Act & Security Compliance',
  },
];
